---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.20.0
  name: ec2instances.compute.cloud.com
spec:
  group: compute.cloud.com
  names:
    kind: Ec2Instance
    listKind: Ec2InstanceList
    plural: ec2instances
    singular: ec2instance
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        description: Ec2Instance is the Schema for the ec2instances API
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            description: spec defines the desired state of Ec2Instance
            properties:
              additionalStorage:
                items:
                  properties:
                    volumeSize:
                      type: integer
                    volumeType:
                      type: string
                  required:
                  - volumeSize
                  - volumeType
                  type: object
                type: array
              amiID:
                type: string
              instanceType:
                type: string
              sshkey:
                type: string
              storage:
                properties:
                  volumeSize:
                    type: integer
                  volumeType:
                    type: string
                required:
                - volumeSize
                - volumeType
                type: object
              subnet:
                type: string
              tags:
                additionalProperties:
                  type: string
                type: object
            required:
            - storage
            - subnet
            - tags
            type: object
          status:
            description: status defines the observed state of Ec2Instance
            properties:
              instanceID:
                type: string
              phase:
                type: string
              publicIP:
                type: string
            type: object
        required:
        - spec
        type: object
    served: true
    storage: true
    subresources:
      status: {}
